---
- block:
    - name: Install dependencies
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install elastalert
      pip:
        name: elastalert
        executable: pip3

    - name: Git checkout from elastalert repo
      git:
        repo: '{{ elastalert_repo }}'
        dest: '{{ temp_folder }}'
    
    - name: Install requirements for python
      pip:
        requirements: '{{ temp_folder }}/requirements.txt'
        executable: pip3
        
  become: true

  